- ES6 语法：[教程](http://es6.ruanyifeng.com/)
- Babel：[教程](http://www.ruanyifeng.com/blog/2016/01/babel.html)
- React：[教程](http://www.ruanyifeng.com/blog/2015/03/react.html)，[示例库](https://github.com/ruanyf/react-demos)
- Webpack：[教程](https://github.com/ruanyf/webpack-demos)
- React 项目脚手架：[代码库](https://github.com/ruanyf/react-babel-webpack-boilerplate)
- Flex 布局：[教程](http://www.ruanyifeng.com/blog/2015/07/flex-grammar.html)，[示例](http://www.ruanyifeng.com/blog/2015/07/flex-examples.html)
- CSS Modules：[教程](http://www.ruanyifeng.com/blog/2016/06/css_modules.html)，[示例库](https://github.com/ruanyf/css-modules-demos)
- React-Router：[教程](http://www.ruanyifeng.com/blog/2016/05/react_router.html)，[示例库](https://github.com/reactjs/react-router-tutorial/tree/master/lessons)
- Flux 架构：[教程](http://www.ruanyifeng.com/blog/2016/01/flux.html)，[示例库](https://github.com/ruanyf/extremely-simple-flux-demo)
- Redux 架构：[教程一](http://www.ruanyifeng.com/blog/2016/09/redux_tutorial_part_one_basic_usages.html)、[教程二](http://www.ruanyifeng.com/blog/2016/09/redux_tutorial_part_two_async_operations.html)、[教程三](http://www.ruanyifeng.com/blog/2016/09/redux_tutorial_part_three_react-redux.html)
- Mocha 测试框架：[教程](http://www.ruanyifeng.com/blog/2015/12/a-mocha-tutorial-of-examples.html)，[示例库](https://github.com/ruanyf/mocha-demos)
- Istanbul 覆盖率框架：[教程](http://www.ruanyifeng.com/blog/2015/06/istanbul.html)
- React 单元测试：[教程](http://www.ruanyifeng.com/blog/2016/02/react-testing-tutorial.html)，[示例库](https://github.com/ruanyf/react-testing-demo)

摘自：http://www.ruanyifeng.com/blog/2016/09/react-technology-stack.html
